### ISSUE TITLE
Deprecated "maxage"; use "maxAge" instead

### ISSUE THREAD

**Issue by aendrew** [koajs/generic-session#104]
I get the following when I use koa-generic-session with koa-passport:

`cookies deprecated "maxage"; use "maxAge" instead node_modules/koa-generic-session/lib/session.js:93:20`

This may be a dupe of #83.

**Comment by Supernerd11** [comment]
I also have this problem, whith koa 2 and koa-convert. I also get an error which may have to do whith this problem.

```
cookies deprecated "maxage"; use "maxAge" instead ../node_modules/koa-generic-session/lib/session.js:93:20

  koa-generic-session set error: .keys required for signed cookies
      at Cookies.set (/home/jonathan/Programming/javascript/chat-app/node_modules/cookies/lib/cookies.js:100:27)
      at Object.set (/home/jonathan/Programming/javascript/chat-app/node_modules/koa-generic-session/lib/session.js:93:20)
      at Object.saveNow (/home/jonathan/Programming/javascript/chat-app/node_modules/koa-generic-session/lib/session.js:283:26)
      at saveNow.next (<anonymous>)
      at onFulfilled (/home/jonathan/Programming/javascript/chat-app/node_modules/co/index.js:65:19)
```

**Comment by dead-horse** [comment]
can you send a PR for this?

**Comment by dangolol** [comment]
I also have this, and i send a PR for this but have some test problems on node 6.x. It's nothing to do with this PR
