### ISSUE TITLE
session store is unavaliable

### ISSUE THREAD

**Issue by kanbekotori** [koajs/generic-session#57]
What is this mean, i just copy your code and run it.

```javascript
var session = require('koa-generic-session');
var redisStore = require('koa-redis');
var koa = require('koa');

var app = koa();
app.keys = ['keys', 'keykeys'];
app.use(session({
  store: redisStore()
}));
...
```
```javascript
Error: session store is unavaliable
      at null._onTimeout (/Users/jiangxingshang/Documents/workspace/WebStorm/Shop/node_modules/koa-generic-session/lib/session.js:105:16)
      at Timer.listOnTimeout (timers.js:110:15)
```

**Comment by dead-horse** [comment]
did you start your redis server?

**Comment by kago54** [comment]
If you did , tell me

**Comment by jspangler** [comment]
Along the same line, what should be the approach on my side if a certain store (redis) is not available? Right now it is timing out but I would prefer the site to continue to load and ignore redis being down or at least have more control of the error being thrown.

```
  lib/session.js:97-108

  store.on('disconnect', function() {
    if (storeStatus !== 'available') return;
    storeStatus = 'pending';
    waitStore = new Promise(function (resolve, reject) {
      setTimeout(function () {
        if (storeStatus === 'pending') storeStatus = 'unavailable';
        reject(new Error('session store is unavailable'));
      }, reconnectTimeout);
      store.once('connect', resolve);
    });

  });
```

**Comment by kanbekotori** [comment]
No, i have no redis server on my computer.

**Comment by dead-horse** [comment]
> No, i have no redis server on my computer.

that's why you got `session store is unavaliable`

**Comment by kanbekotori** [comment]
Thanks, worked!

**Comment by smz8023** [comment]
你好，我在使用过程中，报错：
server error { TypeError: Cannot set property name of  which has only a getter
    at defaultErrorHanlder
