### ISSUE TITLE
maxage与maxAge问题

### ISSUE THREAD

**Issue by yukrain** [koajs/generic-session#83]
compatMaxage 处理了maxAge和maxage兼容，却删除了maxAge。

```
 function compatMaxage(opts) {
   if (opts) {
    opts.maxage = opts.maxage === undefined
      ? opts.maxAge
      : opts.maxage;
    delete opts.maxAge;
  }
}
```

在同时使用koa-sess-mongo-store的源码中获取的是maxAge而不是maxage。这导致一些问题。

```
MongoStore.prototype.set = function *(sid, sess) {
    var maxAge = sess.cookie.maxAge;
    sess.sid = sid;
    sess.ttl = new Date((this.ttl || ('number' == typeof maxAge
      ? maxAge : oneDay)) + Date.now());
    return yield this.col.update({sid: sid}, sess, {upsert: true});
};
```

虽然可以使用beforeSave，在存入mongo之前改一下字段。

```
var sessionConfig = {
    store: new MongoStore(),
    beforeSave: function(ctx, sess){
        ctx.session.cookie.maxAge = sess.cookie.maxage; //兼容 maxAge
    }
};
```

但总感觉兼容性不好,想请教大家怎么解决这个问题??????

**Comment by sumaolin** [comment]
我在window7 开发环境中
``` javascript
this.session = {
  user: userInfo.name,
  email: userInfo.email
}
```

一直报错：
``` JavaScript
koa-generic-session set error: Cannot read property 'maxAge' of undefined
    at MongoStore.set$ (f:\Users\dev\bbs\node_modules\koa-generic-session-mongo\dist\store.js:195:33)
    at tryCatch (f:\Users\dev\bbs\node_modules\babel-runtime\regenerator\runtime.js:72:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (f:\Users\dev\bbs\node_modules\babel-runtime\regenerator\runtime.js:334:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (f:\Users\dev\bbs\node_modules\babel-runtime\regenerator\runtime.js:105:21)
    at onFulfilled (f:\Users\dev\bbs\node_modules\co\index.js:65:19)
    at f:\Users\dev\bbs\node_modules\co\index.js:54:5
    at Object.co (f:\Users\dev\bbs\node_modules\co\index.js:50:10)
    at Object.toPromise (f:\Users\dev\bbs\node_modules\co\index.js:118:63)
    at next (f:\Users\dev\bbs\node_modules\co\index.js:99:29)
    at onFulfilled (f:\Users\dev\bbs\node_modules\co\index.js:69:7)
    at f:\Users\dev\bbs\node_modules\co\index.js:54:5
    at Object.co (f:\Users\dev\bbs\node_modules\co\index.js:50:10)
    at Object.toPromise (f:\Users\dev\bbs\node_modules\co\index.js:118:63)
    at next (f:\Users\dev\bbs\node_modules\co\index.js:99:29)
    at onFulfilled (f:\Users\dev\bbs\node_modules\co\index.js:69:7)
    at f:\Users\dev\bbs\node_modules\co\index.js:54:5
```
尝试在通过beforeSave 解决：
``` javascript
app.use(session({
  store: new MongoStore(config.mongodb),
  beforeSave: function(ctx, sess){
    console.info(sess.cookie); // undefined
  }
}));
```
获取不到cookie的值 ，求助 @yukrain

**Comment by yukrain** [comment]
@sumaolin 设置session应该不能那样直接赋值，你试试这样：
```
this.session.user = userInfo.name;
this.session.email = userInfo.email;
```
另外 要设置cookie的时时长也是
```
  this.session.cookie.maxage = 1000 * 3600 * 24 ;
```
你可以在数据库中看到它的存储结构

**Comment by l2xBrain** [comment]
那就用maxAge怎么样?
```
function compatMaxage(opts) {
  if (opts) {
    opts.maxAge = opts.maxage === undefined
      ? opts.maxAge
      : opts.maxage;
    delete opts.maxage;
  }
}
```
